// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "binaryPath": string;
      "connectionMode": string;
      "apiUrl": string;
      "apiKey": string;
      "chatAgentName": string;
      "autoSave": boolean;
      "showReasoning": boolean;
      "showToolUse": boolean;
      "showTokenCount": boolean;
      "enableDebugMode": boolean;
      "enableCitations": boolean;
      "enableAnnotations": boolean;
      "enableTags": boolean;
    };
  }
}
